name: Auto deploy to github page

on:
  push:
    branches:
      - main

jobs:
  DeployPage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ˜
        uses: actions/checkout@v3.5.3

      - name: Use Node.js 18.x ğŸ‘¨â€ğŸ”§
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Install Dependencies ğŸœ
        run: npm ci

      - name: Build âœ¨ğŸŒŸ
        run: npm run build --if-present

      - name: Deploy ğŸš€ğŸ’–
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}