name: Auto deploy to github page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ˜
        uses: actions/checkout@v3.5.3

      - name: Use Node.js 18.x ğŸ‘¨â€ğŸ”§
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Install Dependencies ğŸœ
        run: npm ci

      - name: Build âœ¨ğŸŒŸ
        run: npm run build --if-present

      - name: Deploy ğŸš€ğŸ’–
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy ğŸš€âœ¨
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact ğŸ˜
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to Github Pages ğŸ’–
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
