name: 6ix4 Automate React Testing

on:
  pull_request:
    branches:
      - main

jobs:
  ReactTester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ˜‰ğŸš¦
        uses: actions/checkout@v4.0.0

      - name: Use Node.js 18.x ğŸ§‘â€ğŸ”§
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Install Dependencies ğŸ
        run: npm ci

      - name: Run Tests by vitest ğŸ¤–
        run: npm test